<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Component\Model\Application\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Account
 *
 * Structure class for relation public.account.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Account extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.account')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('firstname', 'varchar')
            ->addField('lastname', 'varchar')
            ->addField('email', 'varchar')
            ;
    }
}
